### ISSUE TITLE
roll a new release

### ISSUE THREAD

**Issue by SethTisue** [scala/sbt-scala-modules#14]
so we can push the MiMa version bump (#15) out to the modules

**Comment by SethTisue** [comment]
@retronym I took a stab at this, but I'm a Bintray newbie (I know Sonatype well now but have not done Bintray) and I think I may have published 1.0.5 to the wrong place, or maybe it's a right place but not the usual right place? 1.0.5 artifacts are at https://dl.bintray.com/typesafe/sbt-plugins/org.scala-lang.modules/scala-module-plugin/scala_2.10/sbt_0.13/ but that isn't where the other versions were published

rather than fumble around with it more myself, I'm hoping you might remember how this is supposed to work in this repo

**Comment by retronym** [comment]
I remember being confused myself.

https://bintray.com/adriaanm/sbt-plugins/scala-module-plugin
https://bintray.com/retronym/sbt-plugins/scala-module-plugin

![image](https://cloud.githubusercontent.com/assets/65551/21371045/c7020f2c-c75a-11e6-8957-696c656146b4.png)

**Comment by retronym** [comment]
Compared with the `typesafe` bintray account isn't linked to the sbt-plugin-releases aggregating repo.

![image](https://cloud.githubusercontent.com/assets/65551/21371107/0c2ad322-c75b-11e6-8558-e02a882b12f6.png)

**Comment by lrytz** [comment]
Released 1.0.6 and updated the README with instructions how to cut a release.
