### ISSUE TITLE
Scala Days 2017 tickets for Scala module maintainers

### ISSUE THREAD

**Issue by SethTisue** [scala/sbt-scala-modules#22]
@danslapman @biswanaths @ashawley @benhutchison @gourlaysama I don't have email addresses for all of you so this seems like the easiest way to get in touch

would you like to attend Scala Days Copenhagen? we can't pay travel, but Lightbend can offer you a ticket to the conference, as a thank-you for the effort you've put into a maintaining a Scala module. if you want a ticket, please write me at seth.tisue@lightbend.com

sorry there’s so little notice but this is a new idea we only had just now. perhaps it’s too late for you to make plans to come to Copenhagen, but we’re making the offer anyway on the off chance you can make it work

next year, if you're still an active maintainer and you want to go (to either the US or Europe edition), please be in touch once 2018 dates and locations are announced

**Comment by SethTisue** [comment]
@danslapman @ashawley @benhutchison @gourlaysama ping! please write me if interested for 2018. NYC or Berlin, your choice.

**Comment by benhutchison** [comment]
Alas unable to attend this year, presenting a week or so later up at Lambdajam Sydney and my family won't cope with too much time away
