### ISSUE TITLE
deal with classpath issues during bootstrapping

### ISSUE THREAD

**Issue by adriaanm** [scala/sbt-scala-modules#5]
core dependencies are dropped by ivy because of faux circular dependencies

to avoid problem with circular dependency when bootstrapping the modules

```
compilers in (Compile, doc) := {
  val instance = scalaInstance.value
  val cp = (packageBin in Compile).value +: instance.allJars
  println(s"Classpath for scalaInstance =\n\t * ${cp mkString "\n\t * "}")
  val launcher = appConfiguration.value.provider.scalaProvider.launcher
  val newInstance = ScalaInstance(instance.libraryJar, instance.compilerJar, launcher, cp:_*)
  Compiler.compilers(newInstance, classpathOptions.value, javaHome.value)(appConfiguration.value, streams.value.log)
}
```

**Comment by SethTisue** [comment]
@szeiger is this no longer an issue in the 2.12 build?

**Comment by szeiger** [comment]
It's the first time I look at this ticket and I don't understand what it's about. The link above is not stable. I tried to look in the history but it wasn't obvious to me what it's supposed to point at. Since the dependencies on scala-xml haven't changed in 2.12, I have to reason to believe that it would behave any differently than in 2.11.

**Comment by adriaanm** [comment]
It would affect 2.12 in the same way as 2.11. My recollection is that we had to put temporary version number hacks in place in the bootstrap script when documenting the modules because we would be depending on scala-xml (for running  scaladoc) while documenting scala-xml (same version). This cycle caused ivy to drop this artifact from the class path, which would cause scaladoc to fail. The same hack that resolved this in 2.11 is also in place for 2.12 AFAIK

**Comment by ashawley** [comment]
Is this the same issue that causes scala/scala-xml#112 (among others)? Or a different one?

**Comment by adriaanm** [comment]
I haven't investigated closely, but that looks unrelated.

**Comment by SethTisue** [comment]
I am closing this, because I think the solution is to finally just cut the remaining thin dependency of the scaladoc tool on scala-xml, and forbid any such circular dependencies between scala and it modules from ever arising again. circular dependencies are what Pandora's box was full of
