### ISSUE TITLE
Support for multi-project builds

### ISSUE THREAD

**Issue by gkossakowski** [scala/sbt-scala-modules#8]
According to scala/scala-swing#37, the plugin doesn't support multi-project sbt definitions properly.

This is a placeholder issue to be filled with more information once proper investigation is done.

**Comment by andy1138** [comment]
Looks like a issue with sbt, see https://github.com/sbt/sbt/issues/1430.
Updating scala-swing from 0.13.5 to 0.13.7 solved the problem

**Comment by gkossakowski** [comment]
Excellent! Thanks for sharing this!
